<a href="https://colab.research.google.com/github/durgesh2987/Pytorch/blob/master/Intro_Pytorch_Part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch


In [0]:
def activation(x):
  
  return 1/(1+torch.exp(-x))


In [59]:
torch.manual_seed(7)




features = torch.randn((1, 5))

print(features)

weights=torch.randn_like(features)

print(weights)
bias = torch.randn((1, 1))

print(bias)

tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])
tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])
tensor([[0.3177]])


In [60]:
#torch.mm(features,weights)



weights.view(5, 1)

weights.shape
                


y = activation(torch.mm(features, weights.view(5,1)) + bias)

print(y)

tensor([[0.1595]])


In [61]:
torch.manual_seed(7)

feactures=torch.randn((1,3))

print(feactures)

print(feactures.shape)

n_input=feactures.shape[1]

print(n_input)

n_hidden=2
n_output=1

w1=torch.randn(n_input,n_hidden)


print(w1.shape)

w2=torch.randn(n_hidden,n_output)

b1=torch.randn(1,n_hidden)
b2=torch.randn(1,n_output)

y1=activation(torch.mm(feactures,w1+b1))

print(y1)


tensor([[-0.1468,  0.7861,  0.9468]])
torch.Size([1, 3])
3
torch.Size([3, 2])
tensor([[0.6980, 0.4553]])


In [62]:
y1 = activation(torch.mm(feactures, w1) + b1)

print(y1)

y=activation(torch.mm(y1,w2)+b2)

print(y)



tensor([[0.6813, 0.4355]])
tensor([[0.3171]])


In [63]:
torch.manual_seed(7)

feactures=torch.randn(5,10)

weight=torch.randn(10,1)

print(weight)

bias=torch.randn(1,1)

y=activation(torch.mm(feactures,weight)+bias)
print(y)




tensor([[-0.1857],
        [-0.8985],
        [ 0.6095],
        [ 0.2240],
        [ 1.5147],
        [ 0.6119],
        [-0.6075],
        [ 0.8534],
        [ 0.7554],
        [-0.5511]])
tensor([[0.4685],
        [0.9806],
        [0.0731],
        [0.6456],
        [0.9333]])
